import { ThemeConfig } from 'antd/es/config-provider/context';

const themeColors: ThemeConfig['token'] = {
  // colorPrimary: '#1d39c4',
  // colorTextSecondary: '#6c757d',
  // colorError: '#f5222d',
  // colorSuccess: '#28a745',
  // colorWhite: '#fff',
  // colorWarning: '#fa8c16',
  // colorInfo: '#08979c',
  // colorTextHeading: 'colorPrimary',
  // colorPrimaryBg: 'colorPrimary',
  // colorErrorBg: 'colorError',
  // colorSuccessBg: 'colorSuccess',
  // colorWarningBg: 'colorWarning',
  // colorInfoBg: 'colorInfo',
  // colorBorder: '#e8e8e8',
  // colorBgContainer: 'white',
  // colorBgContainer: 'red',
  // colorBgBase: 'blue',
};
const themeScreenSize: ThemeConfig['token'] = {
  // screenLG: 992,
  // screenLGMax: 1199,
  // screenLGMin: 992,
  // screenMD: 768,
  // screenMDMax: 991,
  // screenMDMin: 768,
  // screenSM: 576,
  // screenSMMax: 767,
  // screenSMMin: 576,
  // screenXL: 1200,
  // screenXLMax: 1599,
  // screenXLMin: 1200,
  // screenXS: 480,
  // screenXSMax: 575,
  // screenXSMin: 480,
  // screenXXL: 1600,
  // screenXXLMin: 1600,
};

const themeFont: ThemeConfig['token'] = {
  // fontFamily: ` 'Noto Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
  // 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue' `,
  // fontSizeLG: 16,
  // fontSizeSM: 12,
  // fontSizeXL: 20,
};
const themeBox: ThemeConfig['token'] = {
  // padding: 16,
  // paddingMD: 12,
  // paddingSM: 8,
  // paddingLG: 26,
  // borderRadius: 8,
  // borderRadiusLG: 8,
  // borderRadiusSM: 4,
  // borderRadiusXS: 2,
  // paddingContentHorizontal: 16,
  // lineType: 'solid',
  // lineWidth: 0.5,
  // colorBorderSecondary: `${themeColors?.colorBorder}`,
  // boxShadowSecondary: `rgba(149, 157, 165, 0.2) 0px 8px 24px;`,
  // boxShadow: ` rgba(149, 157, 165, 0.2) 0px 8px 24px;`,
  // fontSize: 14,
  // fontSizeLG: 16,
  // sizeLG: 24,
  // sizeMD: 20,
  // borderRadius: 0,
};
export const defaultToken: ThemeConfig['token'] = {
  ...themeColors,
  ...themeScreenSize,
  ...themeFont,
  ...themeBox,
};
